jobs:
  validate:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: trussworks/circleci:72cdc0285f434a73952ab882a0da1357c613c392
    steps:
    - checkout
    - restore_cache:
        keys:
        - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
    - run:
        command: pre-commit run --all-files --show-diff-on-failure
        name: Run pre-commit tests
    - save_cache:
        key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        paths:
        - ~/.cache/pre-commit

version: 2.1
workflows:
  validate:
    jobs:
    - validate:
        context:
        - org-global
  version: 2.1
